### ISSUE TITLE
Add support for file://hostname/... URLs

### ISSUE THREAD

**Issue by bhaible** [tats/w3m#120]
A growing number of terminal emulators supports hyperlinks in text output. The specification for this feature, based on an escape sequence, is at https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda . Basically, a user opens a terminal emulators, configures a browser to use (for file, http, https URLs), and runs programs that emit hyperlinks, such as `ls --hyperlink` (ls from GNU coreutils).

The specification says that file URLs should have the form "file://hostname/...", where the hostname is the result of gethostname() a.k.a. `uname -n`. (And `ls --hyperlink` in fact produces URLs of this form.) For this to work, the browser needs to understand these URLs, of course. Firefox can, but w3m - which especially some Emacs users set as their default browser - currently does not:

$ uname -n
omega
$ w3m file:///etc/lsb-release
OK
$ w3m file://omega/etc/lsb-release
w3m: Can't load file://omega/etc/lsb-release.

Here is a patch that implements this feature.

**Comment by bhaible** [comment]
[file-hostname-support.diff.gz](https://github.com/tats/w3m/files/3488813/file-hostname-support.diff.gz)

**Comment by tats** [comment]
> file-hostname-support.diff.gz

Merged, thanks for your contribution.
