### ISSUE TITLE
Keys displayed in help change order on reload

### ISSUE THREAD

**Issue by DavidSpickett** [tats/w3m#133]
If I reload/reopen the help page (H) in w3m the order of the assigned keys changes each time. As does the displayed upper case name on the end of the lines. (if it has multiple names)

```
+,C-v,SPC,^[[6~      Scroll down one page (NEXT_PAGE)
ESC-s                Save document source (DOWNLOAD)
```
In the first line the left column will re-order itself on reload, the second line switches from DOWNLOAD to SAVE. (use R to refresh and keep the same position on the page)

This is because the CGI script to display these is iterating over hashes which aren't ordered. (as far as I can tell, I'm new to perl)

I have a patch that fixes this. Is a pull request the way to contribute?

**Comment by tats** [comment]
> I have a patch that fixes this. Is a pull request the way to contribute?

Yes, please make a pull request to contribute.
