### ISSUE TITLE
Unknown URI issue. Cant load any URL

### ISSUE THREAD

**Issue by danrobi11** [tats/w3m#172]
Hi. I just compiled w3m and w3m cant load anything.

Says ```Unknown URI``` and return with ```Cant load``` with any URL

Theres no install instruction. So heres what I did:

- ./configure
- make
- sudo make install

Something else I should do ?
The help says -debug DO NOT USE is this still relevant ?

->./w3m -version
w3m version w3m/0.5.3+git20210102, options lang=en,m17n,image,color,ansi-color,mouse,menu,cookie,external-uri-loader,w3mmailer,nntp,gopher,ipv6,alarm,mark

OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm 

Thank you for maintaining w3m

**Comment by danrobi11** [comment]
Also cant load the config file with ```REINIT```

->./w3m REINIT
w3m: Can't load REINIT.

**Comment by danrobi11** [comment]
Ok this seems to have fixed the issue

- ./w3m -config file /home/danrobi/.local/bin/w3m/config.h

Not sure that fixed the issue but now w3m is working. Therefore closing

**Comment by reportaman** [comment]
@danrobi11 I get the same problem. What does this command mean? ``./w3m -config file /home/danrobi/.local/bin/w3m/config.h``. w3m does not have a ``-config`` option.

**Comment by danrobi11** [comment]
@reportaman means to specicy where the config file is location with ```-config file``` 

But I still got issue with this. I'll edit the comment above and reopen the issue.

**Comment by reportaman** [comment]
@danrobi11 My issue is resolved, check the answer from @tats there: https://github.com/tats/w3m/issues/173#issuecomment-789288364

**Comment by danrobi11** [comment]
@reportaman Thanks for sharing. I fixed the issue by installing libssl-dev like @borkabrak mentionned in #173
