### ISSUE TITLE
Can't most load URI other than google or bing

### ISSUE THREAD

**Issue by reportaman** [tats/w3m#173]
Hi,

I cannot load any URI other than google.com or bing.com. Example: linkedin.com, etc. I built w3m myself on ARM64 Apple Silicon macOS. Do I need to configure something that I don't know? One observation is that it is able to expand the URI's to correct full values. For instance if I type ``>>w3m linkedin.com``, I get a blank screen stating ``"Unknown URI: https://www.linkedin.com"``

```
>>w3m -version
w3m version w3m/0.5.3+git20210302, options lang=en,m17n,image,color,ansi-color,mouse,menu,cookie,external-uri-loader,w3mmailer,nntp,gopher,ipv6,alarm,mark
```

**Comment by tats** [comment]
It seems SSL is not detected by ./configure.

Please use `--with-ssl` to specify the location of "include/openssl/ssl.h"
or "include/ssl.h".  e.g. `./configure --with-ssl=/opt/openssl`.

By default, the location is auto-detected with "/usr/openssl /usr/ssl /usr
/usr/local/openssl /usr/local/ssl /usr/local".

Please tell me your ssl.h location.  I'll consider to add it for
the auto-detection.

**Comment by reportaman** [comment]
@tats Thanks! adding ``--with-ssl=<path to top directory that has open ssl include, lib etc dirs>`` resolved the issue. No need to add it to auto-detection, as currently Apple Silicon maOS's home-brew suggests installing in a non-standard location (so the x86 binaries don't mix with ARM). That problem will be resolved over time, and users will not need to use non-standard paths. This really should be a error IMO, as it is pretty much unusable without ssl.h.

**Comment by borkabrak** [comment]
I was able to resolve this by installing the libssl-dev package.  It may be worthwhile to list both libssl-dev and libgc-dev as dependencies, if that's not too Debian-centric.

**Comment by danrobi11** [comment]
@borkabrak Thanks for sharing. Installing libssl-dev did fix the issue.
