### ISSUE TITLE
Won't open local files with colon in filename 

### ISSUE THREAD

**Issue by rolfmorel** [tats/w3m#190]
I have a use case of loads of local HTML files, without extensions, which at times include a colon (':') in their filename. w3m gets confused by this, thinking that anything up to the colon is the URI scheme.

Reproducible example:
```
$ wget https://github.com/tats/w3m
$ w3m -T text/html w3m
# observe that w3m correctly displays the page
$ mv w3m "w3m: WWW wo Miru Tool"
$ w3m -T text/html "w3m: WWW wo Miru Tool"
# w3m only displays message "Unknown URI: w3m:%20WWW%20wo%20Miru%20Tool" before outputting: 
w3m: Can't load w3m: WWW wo Miru Tool.
```

I have been unable to find a workaround. I have looked at the (complex) code in url.c. This gave me the idea to try "file://" and "local://" prefixes. I also found the option `argv_is_url=0`, which sounds like the right thing but doesn't work when there is a colon in the filename.

**Comment by Boruch-Baum** [comment]
On 2021-08-23 13:42, Rolf Morel wrote:
>    I have a use case of loads of local HTML files, without extensions,
>    which at times include a colon (':') in their filename. w3m gets
>    confused by this, thinking that anything up to the colon is the URI
>    scheme.

Does this work? Does the example help?

  echo '<html><body><h1>hello neighborhood!</h1></body></html>' > 'a:b.html'
  w3m file:///home/optimum/Downloads/a:b.html

Also, from within a w3m session, with (what I think is the ) the default
keybindings, try 'V' and then enter a path-name without a method prefix
(ie. no need for file:///). This second method gives you tab completion
for file-name candidates.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by rolfmorel** [comment]
Thanks for these tips. It got me to the right solution.

For using full paths, starting from the filesystem's root, your suggestion works: `file://` followed by the full path, which adds an additional `/` at the start.
While relative `file:` URIs do not exist according to the standard, w3m does support them. It is the most straightforward syntax: `file:RELPATH` where RELPATH can be any filename, no need for any leading slashes.

Note that the above works independent of a file extension being present. If, like me, you don't have an extension on your files, use the `-T text/html` option.
