### ISSUE TITLE
w3mman does not render ansi escape sequences on redhat based distributions

### ISSUE THREAD

**Issue by albfan** [tats/w3m#201]
OS: Fedora 34 
package: w3m-0.5.3-50.git20210102.fc34.x86_64

Man pages add ansi escape sequences for bold

```
$ PAGER='cat -A' /usr/bin/man bash
BASH(1)                                                                                                  General Commands Manual                                                                                                  BASH(1)$
$
^[[1mNAME^[[0m$
       bash - GNU Bourne-Again SHell$
$
^[[1mSYNOPSIS^[[0m$
       ^[[1mbash ^[[22m[options] [command_string | file]$
$
^[[1mCOPYRIGHT^[[0m$
       Bash is Copyright (C) 1989-2020 by the Free Software Foundation, Inc.$
$
^[[1mDESCRIPTION^[[0m$
...
```

On bash it shows correctly:

```
$ /usr/bin/man bash
BASH(1)                                                                                                  General Commands Manual                                                                                                  BASH(1)

NAME
       bash - GNU Bourne-Again SHell

SYNOPSIS
       bash [options] [command_string | file]

COPYRIGHT
       Bash is Copyright (C) 1989-2020 by the Free Software Foundation, Inc.

DESCRIPTION
...
```

But w3mman do not render those correctly:

```
$ /usr/bin/w3mman bash
BASH(1)                                                                                                  General Commands Manual                                                                                                  BASH(1)

 [1mNAME [0m
       bash - GNU Bourne-Again SHell

 [1mSYNOPSIS [0m
        [1mbash  [22m[options] [command_string | file]

 [1mCOPYRIGHT [0m
       Bash is Copyright (C) 1989-2020 by the Free Software Foundation, Inc.

 [1mDESCRIPTION [0m
...
```

Any settings I'm missing? I see this working correctly on arch linux

**Comment by hboetes** [comment]
Please change the title to `w3mman do not render ansi escape sequences on redhat based distributions`

That's a more accurate description of what's going on.

**Comment by hboetes** [comment]
`/usr/local/libexec/w3m/cgi-bin/w3mman2html.cgi man > man.html`

generates proper html on other platforms, but on redhat and friends the resulting output contains escape codes.

**Comment by hboetes** [comment]
I compiled man-db like it's compiled on [https://github.com/archlinux/svntogit-packages/blob/packages/man-db/trunk/PKGBUILD](arch), and I get exactly the same problem...

**Comment by albfan** [comment]
Arch linux.

    /usr/lib/w3m/cgi-bin/w3mman2html.cgi man >man.html

```
$ head man.html 
Content-Type: text/html

<html>
<head><title>man man</title></head>
<body>
<pre>
MAN(1)                                                            Utilidades de paginador del manual                                                           MAN(1)

<b>NOMBRE</b>
       man - interfaz de los manuales de referencia del sistema
```

**Comment by albfan** [comment]
I started adding substitute commands:

```
diff --git i/w3mman2html.cgi w/w3mman2html.cgi
index b121470..6c3d0c0 100755
--- i/w3mman2html.cgi
+++ w/w3mman2html.cgi
@@ -162,7 +162,6 @@ EOF
     next;
   }
 
-  s@[1m(\w+)[0m$@<b>$1</b>@g;
   s@(http|ftp)://[\w.\-/~]+[\w/]@<a href="$&">$&</a>@g;
   s@\b(mailto:|)(\w[\w.\-]*\@\w[\w.\-]*\.[\w.\-]*\w)@<a href="mailto:$2">$1$2</a>@g;
   s@(\W)(\~?/[\w.][\w.\-/~]*)@$1 . &file_ref($2)@ge;
```

and starts to work.  I will submit a PR when is ready

**Comment by hboetes** [comment]
Please commit #238 
Thanks!

**Comment by hboetes** [comment]
I have found one still, `[34m` in `dbus-run-session(1)`

**Comment by rkta** [comment]
On Sat, Dec 24, 2022 at 11:18:08AM -0800, Han Boetes wrote:
> I have found one still, `[34m` in `dbus-run-session(1)`

This sounds like we want a test for this. I'm not into the topic, atm,
but maybe something like how we test entities.

**Comment by albfan** [comment]
So finally setting missed is

    GROFF_NO_SGR=1

https://github.com/tats/w3m/compare/8891eab5b55647d8f2ab5a8dd9754c660200c280...760d7ad7295bb762a7bef3f5dc17b58278a06ac4

Wonder if we should reopen this and consider a parameter to configure depending on distro. Or this just force same behaviour in all distros?

**Comment by tats** [comment]
I assume adding GROFF_NO_SGR=1 has no problem with

  - groff >=1.18 with Debian default
  - groff >=1.18 default
  - groff <1.18, or
  - non-groff.

I don't assume SGR is forcely enabled even when GROFF_NO_SGR=1.

Anyway, if you really found a problem, please reopen.
