### ISSUE TITLE
w3m does not handle all valid file names

### ISSUE THREAD

**Issue by rkta** [tats/w3m#210]
w3m does not handle all valid file names

% touch a\#a.html b\?b.html c\%20.html
% w3m a\#a.html b\?b.html c\%20.html
w3m: Can't load a#a.html.
w3m: Can't load b?b.html.
w3m: Can't load c%20.html.

% w3m file://$PWD/c%20.html
w3m: Can't load file:///tmp/tmp.VPiZ2er7xp/c%20.html.

Note, that it also fails with other names that contain percent-encoded
chars.

**Comment by rkta** [comment]
Previous BTS report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=537761

**Comment by rkta** [comment]
JFTR, one way to get it to work:

Go to 'Option Setting Panel' -> 'Network Settings',
set 'Treat argument without scheme as URL' to 'NO'.

Caveat:
 - 'w3m debian.org' doesn't work any more. You need to use
 - 'w3m https://debian.org' works.

I still consider this a bug.

**Comment by tats** [comment]
Fixed by https://github.com/tats/w3m/pull/235
