### ISSUE TITLE
For a predefined domain, go to the Nth line after the page loads?

### ISSUE THREAD

**Issue by 097115** [tats/w3m#211]
Is it possible to script something like this? With `siteconf`'s help, probably?

Like, if we open https://abc.com/page1, then, as soon as the page loads, cursor is placed on the 30th line, for example (and it would be great to place that line at the top of the buffer).

I imagine I place something like this in the `siteconf`:

    url m@^https?://(www.)?abc\.com/@
    substitute_url "file:/cgi-bin/abc_com.cgi?"

But what do I put in that `abc_com.cgi`? Tried something like that:

     #!/bin/bash
     printf "%s\r\n" "W3m-control: GOTO ${W3M_URL}"
     printf "%s\r\n" "W3m-control: GOTO_LINE 30"

...but it doesn't seem to work :(

**Comment by bptato** [comment]
Try $QUERY_STRING instead of ${W3M_URL}.

**Comment by 097115** [comment]
@bptato, thanks for your help! 

Got it working with `$QUERY_STRING` and this `siteconf` entry:

    url m@^https?://abc\.com/@
    substitute_url "file:/cgi-bin/abc.cgi?https://www.abc.com/"

i.e., redirecting from a www-less page to an URL with www. Otherwise, it seems, it's just entered an infinite redirect :)
