### ISSUE TITLE
Images don't work with Imlib2 v1.7.5

### ISSUE THREAD

**Issue by N-R-K** [tats/w3m#213]
Hi,

While trying to compile w3m with imlib2 support, I see the following:

```console
checking image library... imlib2
configure: WARNING: Imlib2 is not installed.  Install Imlib2 (version >= 1.0.5)
configure: WARNING: unable to build w3mimgdisplay with X11 support
```

I think this is because it's trying to use `imlib2-config` which has been dropped by imlib2 : https://git.enlightenment.org/legacy/imlib2.git/commit/?id=e9d84bd2163e6fab494b5ce5cc8830a54ff97765

**Comment by N-R-K** [comment]
@rkta I'm on bit of an older version (the gentoo ebuild isn't using the latest commit), but the patch still applied and images are working correctly now.

**Comment by N-R-K** [comment]
Closing this since #215 was merged. @tats giving you a ping, since I'm assuming you didn't notice this (since you haven't closed the issue nor mentioned it on the ChangeLog).

**Comment by rkta** [comment]
On Thu, Feb 17, 2022 at 03:53:38AM -0800, N-R-K wrote:
> Closing this since #215 was merged. @tats giving you a ping, since I'm assuming you didn't notice this (since you haven't closed the issue nor mentioned it on the ChangeLog).

Interesting, the issue was mentioned in the commit - that should
automagically close the issue.
