### ISSUE TITLE
Bug: soft hyphen handling

### ISSUE THREAD

**Issue by Seirdy** [tats/w3m#224]
Soft hyphens denoted by the `&shy;` entity are always rendered as hyphens in w3m, even when the line isn't broken.

For example, the "Acknowledgements" heading in [this page](https://seirdy.one/2021/03/10/search-engines-with-own-indexes.html) is contains a soft-hyphen (`Acknowledge&shy;ments`). w3m displays this text:

```
Acknowledge­ments
```

A web browser displays the above text without a hyphen; however, pasting that text into a terminal will likely result in text that looks like this:

```
Acknowledge-ments
```

This is because terminal emulators display the [soft hyphen character](https://en.wikipedia.org/wiki/Soft_hyphen) while web browsers only display it when wrapping text.

w3m shouldn't print the soft hyphen unconditionally: it should only print a regular when wrapping text, or should just remove it altogether.

**Comment by rkta** [comment]
On Fri, Mar 11, 2022 at 01:04:49AM -0800, Rohan Kumar wrote:
> Soft hyphens denoted by the `&shy;` entity are always rendered as
> hyphens in w3m, even when the line isn't broken.

JFTR, previous bug report on BTS:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830173

**Comment by tats** [comment]
Fixed by https://github.com/tats/w3m/pull/256
