### ISSUE TITLE
Translating first strings

### ISSUE THREAD

**Issue by alexandre1985** [tats/w3m#225]
I am trying to make the translation of w3m to Portuguese.

I have a doubt about the first strings of the po file.
They are something like " Back        (b)" and I wonder why the spacing. It must be a menu that has the key shortcut in it.
I have noticed that all of this type of strings have equal spacing so I believe it is important to mantain an equal length string, in all of this strings type. But I have the problem that Portuguese translation words are too big for this string length. So I don't know if I can extend all of this string's length. And if it fits well the menu.

I also would like to know, how, in w3m, can I access this strings menu, to check if my translation fits well with all the spacing and length. I need it for testing my translations.

The menu's strings in question are the strings from " Back      (b) " until " Quit      (q) ".

Thanks

**Comment by tats** [comment]
> So I don't know if I can extend all of this string's length.
> I also would like to know, how, in w3m, can I access this strings menu,

The length can be extended with equal spacing.  cf. de.po
To display the menu in w3m, type `[Esc] c MENU [Enter]`, or
click the right button of the mouse on xterm or so.

**Comment by alexandre1985** [comment]
It worked. Thank you
