### ISSUE TITLE
Doesnt work at all on linux mint

### ISSUE THREAD

**Issue by FuckOBS** [tats/w3m#243]
I've just about tried it with every terminal I can
Xfce-4 Terminal
Terminator
Terminology
Xterm
Kitty
Alacritty
But yet none of them work with this one little program, 1. Doesn't even work with   6 different terminals. Now how the hell is that?

**Comment by yashlala** [comment]
_How_ does the program "not work"? Are the graphics messed up? Is there an error message? Can you send screenshots or additional information? Without any additional information, it's impossible to solve the problem. But providing constructive feedback can help us work out this issue together.

For example, if the visuals are messed up, we might guess that the problem has to do with the terminal. If your program failed with an error message of "no config file found", then we'd know that problem has nothing to do with Terminator vs Xterm vs Kitty.

**Comment by Boruch-Baum** [comment]
@yashlala : What I did was carefully read the OP user name, ask what type of person chooses such a username, then I navigated to the OP user page to get a better look at the OP avatar, ask what type of person chooses such an avatar, then I browsed through the OP github contribution history. After all that, I decided to ignore him, and based upon al that I recommend that @tats just close this issue.

**Comment by yashlala** [comment]
I figured OP was likely a kid. I had a minute to spare, so I tried for a teaching moment.

**Comment by N-R-K** [comment]
As long as he can provide more details on *how* it "doesn't work" then someone can try and solve the issue, the username or pfp is irrelavent (imo). But just saying something "doesn't work" is not useful information because it works fine on my machine :tm:

**Comment by tats** [comment]
More info needed.
