### ISSUE TITLE
Socks5 support

### ISSUE THREAD

**Issue by lmaddox** [tats/w3m#306]
SOCKS_PROXY=127.0.0.1:9050 w3m ifconfig.me resolves to my public address. Same result with socks5://127.0.0.1:9050

**Comment by rkta** [comment]
On Mon, Oct 07, 2024 at 08:32:04AM -0700, ਬ੍ਰਹ੍ਮ੍ਜੋਤ ਸਿੰਘ ਖਾਲਸਾ wrote:
> SOCKS_PROXY=127.0.0.1:9050 w3m ifconfig.me resolves to my public
> address.

This is expected as w3m does not look for SOCKS_PROXY in the
environment.

> Same result with socks5://127.0.0.1:9050

This gives me:
Unknown URI: socks5://127.0.0.1:9050
w3m: Can't load socks5://127.0.0.1:9050.

**Comment by lmaddox** [comment]
thanks for the tip. proxychains seems to make it work as expected
