### ISSUE TITLE
Errors building from source

### ISSUE THREAD

**Issue by Boruch-Baum** [tats/w3m#45]
Just now I downloaded a zip file of the sources, and the 'make' has failed twice so far:

1] html.h is missing an "include" for <time.h>

2] terms.c is missing includes for "<term.h>" and "<curses.h>"

3] terms.c is still failing to compile. Here is the current output of my "make".

~~~

hgcc  -I. -I. -g -O2 -I./libwc  -DHAVE_CONFIG_H -DAUXBIN_DIR=\"/home/optimum/Projects/w3m/w3m-installed/libexec/w3m\" -DCGIBIN_DIR=\"/home/optimum/Projects/w3m/w3m-installed/libexec/w3m/cgi-bin\" -DHELP_DIR=\"/home/optimum/Projects/w3m/w3m-installed/share/w3m\" -DETC_DIR=\"/home/optimum/Projects/w3m/w3m-installed/etc\" -DCONF_DIR=\"/home/optimum/Projects/w3m/w3m-installed/etc/w3m\" -DRC_DIR=\"~/.w3m\" -DLOCALEDIR=\"/home/optimum/Projects/w3m/w3m-installed/share/locale\"   -c -o terms.o terms.c
In file included from terms.c:17:0:
hash.h:15:27: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘->’ token
   struct HashItem_##sym **tab; \
                           ^
hash.h:21:1: note: in expansion of macro ‘defhash’
 defhash(char *, int, si)
 ^
hash.h:15:27: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘->’ token
   struct HashItem_##sym **tab; \
                           ^
hash.h:22:1: note: in expansion of macro ‘defhash’
 defhash(char *, char *, ss)
 ^
hash.h:15:27: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘->’ token
   struct HashItem_##sym **tab; \
                           ^
hash.h:23:1: note: in expansion of macro ‘defhash’
 defhash(char *, void *, sv)
 ^
hash.h:15:27: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘->’ token
   struct HashItem_##sym **tab; \
                           ^
hash.h:24:1: note: in expansion of macro ‘defhash’
 defhash(int, void *, iv)
 ^
proto.h:288:41: error: expected ‘;’, ‘,’ or ‘)’ before ‘->’ token
 extern TabBuffer *deleteTab(TabBuffer * tab);
                                         ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:470:12: error: conflicting types for ‘initscr’
 extern int initscr(void);
            ^
In file included from terms.c:18:0:
/usr/include/curses.h:646:33: note: previous declaration of ‘initscr’ was here
 extern NCURSES_EXPORT(WINDOW *) initscr (void);    /* implemented */
                                 ^
proto.h:471:13: error: expected ‘)’ before ‘(’ token
 extern void move(int line, int column);
             ^
proto.h:475:13: error: expected ‘)’ before ‘(’ token
 extern void addch(char c);
             ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:478:26: error: macro "standout" passed 1 arguments, but takes just 0
 extern void standout(void);
                          ^
proto.h:478:13: error: ‘standout’ redeclared as different kind of symbol
 extern void standout(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:776:28: note: previous declaration of ‘standout’ was here
 extern NCURSES_EXPORT(int) standout (void);    /* generated */
                            ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:479:26: error: macro "standend" passed 1 arguments, but takes just 0
 extern void standend(void);
                          ^
proto.h:479:13: error: ‘standend’ redeclared as different kind of symbol
 extern void standend(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:777:28: note: previous declaration of ‘standend’ was here
 extern NCURSES_EXPORT(int) standend (void);    /* generated */
                            ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:493:25: error: macro "refresh" passed 1 arguments, but takes just 0
 extern void refresh(void);
                         ^
proto.h:493:13: error: ‘refresh’ redeclared as different kind of symbol
 extern void refresh(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:743:28: note: previous declaration of ‘refresh’ was here
 extern NCURSES_EXPORT(int) refresh (void);    /* generated */
                            ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:494:23: error: macro "clear" passed 1 arguments, but takes just 0
 extern void clear(void);
                       ^
proto.h:494:13: error: ‘clear’ redeclared as different kind of symbol
 extern void clear(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:603:28: note: previous declaration of ‘clear’ was here
 extern NCURSES_EXPORT(int) clear (void);    /* generated */
                            ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:502:26: error: macro "clrtoeol" passed 1 arguments, but takes just 0
 extern void clrtoeol(void);
                          ^
proto.h:502:13: error: ‘clrtoeol’ redeclared as different kind of symbol
 extern void clrtoeol(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:606:28: note: previous declaration of ‘clrtoeol’ was here
 extern NCURSES_EXPORT(int) clrtoeol (void);    /* generated */
                            ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:504:26: error: macro "clrtobot" passed 1 arguments, but takes just 0
 extern void clrtobot(void);
                          ^
proto.h:504:13: error: ‘clrtobot’ redeclared as different kind of symbol
 extern void clrtobot(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:605:28: note: previous declaration of ‘clrtobot’ was here
 extern NCURSES_EXPORT(int) clrtobot (void);    /* generated */
                            ^
In file included from terms.c:18:0:
proto.h:507:13: error: expected ‘)’ before ‘(’ token
 extern void addstr(char *s);
             ^
proto.h:508:13: error: expected ‘)’ before ‘(’ token
 extern void addnstr(char *s, int n);
             ^
In file included from fm.h:1242:0,
                 from terms.c:56:
proto.h:510:24: error: macro "crmode" passed 1 arguments, but takes just 0
 extern void crmode(void);
                        ^
proto.h:511:26: error: macro "nocrmode" passed 1 arguments, but takes just 0
 extern void nocrmode(void);
                          ^
proto.h:520:23: error: macro "getch" passed 1 arguments, but takes just 0
 extern char getch(void);
                       ^
proto.h:520:13: error: ‘getch’ redeclared as different kind of symbol
 extern char getch(void);
             ^
In file included from terms.c:18:0:
/usr/include/curses.h:631:28: note: previous declaration of ‘getch’ was here
 extern NCURSES_EXPORT(int) getch (void);    /* generated */
                            ^
In file included from terms.c:17:0:
proto.h:521:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘->’ token
 extern void bell(void);
             ^
terms.c:452:12: error: conflicting types for ‘tgetent’
 extern int tgetent(char *, char *);
            ^
In file included from terms.c:17:0:
/usr/include/term.h:765:28: note: previous declaration of ‘tgetent’ was here
 extern NCURSES_EXPORT(int) tgetent (char *, const char *);
                            ^
terms.c:453:12: error: conflicting types for ‘tgetnum’
 extern int tgetnum(char *);
            ^
In file included from terms.c:17:0:
/usr/include/term.h:767:28: note: previous declaration of ‘tgetnum’ was here
 extern NCURSES_EXPORT(int) tgetnum (NCURSES_CONST char *);
                            ^
terms.c:454:12: error: conflicting types for ‘tgetflag’
 extern int tgetflag(char *);
            ^
In file included from terms.c:17:0:
/usr/include/term.h:766:28: note: previous declaration of ‘tgetflag’ was here
 extern NCURSES_EXPORT(int) tgetflag (NCURSES_CONST char *);
                            ^
terms.c:455:14: error: conflicting types for ‘tgetstr’
 extern char *tgetstr(char *, char **);
              ^
In file included from terms.c:17:0:
/usr/include/term.h:763:31: note: previous declaration of ‘tgetstr’ was here
 extern NCURSES_EXPORT(char *) tgetstr (NCURSES_CONST char *, char **);
                               ^
terms.c:456:14: error: conflicting types for ‘tgoto’
 extern char *tgoto(char *, int, int);
              ^
In file included from terms.c:17:0:
/usr/include/term.h:764:31: note: previous declaration of ‘tgoto’ was here
 extern NCURSES_EXPORT(char *) tgoto (const char *, int, int);
                               ^
terms.c:457:12: error: conflicting types for ‘tputs’
 extern int tputs(char *, int, int (*)(char));
            ^
In file included from terms.c:17:0:
/usr/include/term.h:768:28: note: previous declaration of ‘tputs’ was here
 extern NCURSES_EXPORT(int) tputs (const char *, int, int (*)(int));
                            ^
terms.c:458:1: warning: parameter names (without types) in function declaration
 void clear(), wrap(), touch_line(), touch_column(int);
 ^
In file included from terms.c:18:0:
terms.c:458:6: error: conflicting types for ‘wclear’
 void clear(), wrap(), touch_line(), touch_column(int);
      ^
/usr/include/curses.h:815:28: note: previous declaration of ‘wclear’ was here
 extern NCURSES_EXPORT(int) wclear (WINDOW *);    /* implemented */
                            ^
terms.c:462:19: error: macro "clrtoeol" passed 1 arguments, but takes just 0
 void clrtoeol(void);  /* conflicts with curs_clear(3)? */
                   ^
terms.c:462:6: error: ‘clrtoeol’ redeclared as different kind of symbol
 void clrtoeol(void);  /* conflicts with curs_clear(3)? */
      ^
In file included from terms.c:18:0:
/usr/include/curses.h:606:28: note: previous declaration of ‘clrtoeol’ was here
 extern NCURSES_EXPORT(int) clrtoeol (void);    /* generated */
                            ^
terms.c:1138:1: error: conflicting types for ‘initscr’
 initscr(void)
 ^
In file included from terms.c:18:0:
/usr/include/curses.h:646:33: note: previous declaration of ‘initscr’ was here
 extern NCURSES_EXPORT(WINDOW *) initscr (void);    /* implemented */
                                 ^
terms.c:1161:1: error: expected ‘)’ before ‘(’ token
 move(int line, int column)
 ^
terms.c:1207:1: error: expected ‘)’ before ‘(’ token
 addch(char c)
 ^
terms.c:1413:14: error: macro "standout" passed 1 arguments, but takes just 0
 standout(void)
              ^
terms.c:1414:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:1419:14: error: macro "standend" passed 1 arguments, but takes just 0
 standend(void)
              ^
terms.c:1420:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:1527:13: error: macro "refresh" passed 1 arguments, but takes just 0
 refresh(void)
             ^
terms.c:1528:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:1726:11: error: macro "clear" passed 1 arguments, but takes just 0
 clear(void)
           ^
terms.c:1727:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:1856:14: error: macro "clrtoeol" passed 1 arguments, but takes just 0
 clrtoeol(void)
              ^
terms.c:1857:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {    /* Clear to the end of line */
 ^
terms.c:1927:14: error: macro "clrtobot" passed 1 arguments, but takes just 0
 clrtobot(void)
              ^
terms.c:1928:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from terms.c:18:0:
terms.c:1950:1: error: expected ‘)’ before ‘(’ token
 addstr(char *s)
 ^
terms.c:1967:1: error: expected ‘)’ before ‘(’ token
 addnstr(char *s, int n)
 ^
terms.c:2013:12: error: macro "crmode" passed 1 arguments, but takes just 0
 crmode(void)
            ^
terms.c:2015:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:2031:14: error: macro "nocrmode" passed 1 arguments, but takes just 0
 nocrmode(void)
              ^
terms.c:2033:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
terms.c:2134:11: error: macro "getch" passed 1 arguments, but takes just 0
 getch(void)
           ^
terms.c:2135:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from terms.c:17:0:
terms.c:2234:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘->’ token
 bell(void)
 ^
<builtin>: recipe for target 'terms.o' failed
make: *** [terms.o] Error 1

**Comment by tats** [comment]
Could you please provide more information (OS version, compiler version,
configure log, etc.) to reproduce your problem on my environment?

Patches welcome.

**Comment by Boruch-Baum** [comment]
Sure. Sorry about that.
The environment is debian, with a gnu toolchain including:

$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2

$ autoconf --version
autoconf (GNU Autoconf) 2.69

$ automake --version
automake (GNU automake) 1.14.1

Github is giving me trouble attaching the output of "configure", so here it is, in-line:

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gawk... gawk
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for perl... /usr/bin/perl
checking for nkf... no
checking for man... /usr/bin/man
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if m17n support is enabled... yes
checking if unicode support is enabled... yes
checking if message l10n... no
checking if japanese support is enabled... no
checking which charset is used for display... UTF-8
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking if color escape sequence for kterm/pxvt is enabled... yes
checking if ansi color escape sequence support is enabled... yes
checking if background color support is enabled... yes
checking if image is enabled... yes
checking image library... gtk2 gdk-pixbuf imlib imlib2
configure: WARNING: GdkPixbuf is not installed.  Install GdkPixbuf (version >= 2.0.0)
configure: WARNING: GdkPixbuf is not installed.  Install GdkPixbuf (version >= 0.16.0)
configure: WARNING: Imlib is not installed.  Install Imlib (version >= 1.9.8)
configure: WARNING: Imlib2 is not installed.  Install Imlib2 (version >= 1.0.5)
configure: WARNING: unable to build w3mimgdisplay with X11 support
configure: WARNING: unable to build w3mimgdisplay with FB support
checking if xface is enabled... yes
checking for uncompface... no
configure: WARNING: uncompface is not installed.
checking default keymap... w3m
checking if popup menu is enabled... yes
checking if mouse operation enabled... yes
checking if URL history is enabled... yes
checking if alarm is enabled... yes
checking if cookie is enabled... yes
checking if nntp is enabled... yes
checking if gopher is enabled... no
checking if dictionary lookup is enabled... yes
checking if help cgi is enabled... yes
checking if external URI loader is enabled... yes
checking if w3mmail is used... yes
checking if migemo is supported with... migemo -t egrep /usr/local/share/migemo/migemo-dict
checking which editor is used by default... /usr/bin/vi
checking which mailer is used by default... /usr/bin/mail
checking which external browser is used by default... /usr/bin/firefox
checking for -lbsd... not found
checking for -lBSD... not found
checking for -l44bsd... not found
checking for -lsocket... not found
checking for -lnsl... not found
checking for -ldld... not found
checking for -ldl... not found
checking if IPv6 support is enabled... yes
checking if IPv6 API available... checking for getaddrinfo... yes
checking if struct sockaddr_storage has an ss_family member... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if SSL is suported... yes
checking for SSL... no
checking for SSL library/header... /usr/openssl /usr/ssl /usr /usr/local/openssl /usr/local/ssl /usr/local
checking for SSL_new in -lssl... no
checking if digest auth is enabled... no
checking for sqrt... no
checking for sqrt in -lm... yes
checking for Gpm_Open in -lgpm... no
checking terminal library... yes
checking for tgetent in -lterminfo... no
checking for tgetent in -lmytinfo... no
checking for tgetent in -ltermlib... no
checking for tgetent in -ltermcap... no
checking for tgetent in -ltinfo... no
checking for tgetent in -lncurses... no
checking for tgetent in -lcurses... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking GC library exists... yes
checking gc.h usability... yes
checking gc.h presence... yes
checking for gc.h... yes
checking for GC_init in -lgc... yes
checking for zError in -lz... yes
checking for socklen_t... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking size of long long... 8
checking for strcasecmp... yes
checking for strcasestr... yes
checking for strchr... yes
checking for memcpy... yes
checking for strerror... yes
checking for bcopy... yes
checking for setpgrp... yes
checking for chdir... yes
checking for getcwd... yes
checking for getwd... yes
checking for readlink... yes
checking for setenv... yes
checking for putenv... yes
checking for strtoll... yes
checking for stroq... no
checking for atoll... yes
checking for atoq... no
checking for symlink... yes
checking for readlink... (cached) yes
checking for lstat... yes
checking for srand48... yes
checking for srandom... yes
checking for getpassphrase... no
checking for waitpid... yes
checking for setlocale... yes
checking for strftime... yes
checking for wait3 that fills in rusage... yes
checking whether setpgrp takes no argument... yes
checking for nl_langinfo and CODESET... yes
checking for sys_errlist... yes
checking for sigsetjmp... yes
checking return type of signal handlers... void
configure: creating ./config.status
config.status: creating Makefile
config.status: creating posubst
config.status: creating po/Makefile.in
config.status: creating scripts/Makefile
config.status: creating scripts/dirlist.cgi
config.status: creating scripts/w3mhelp.cgi
config.status: creating scripts/w3mmail.cgi
config.status: creating scripts/xface2xpm
config.status: creating scripts/multipart/Makefile
config.status: creating scripts/multipart/multipart.cgi
config.status: creating scripts/w3mman/Makefile
config.status: creating scripts/w3mman/w3mman
config.status: creating scripts/w3mman/w3mman.1
config.status: creating scripts/w3mman/w3mman.de.1
config.status: creating scripts/w3mman/w3mman2html.cgi
config.status: creating libwc/Makefile
config.status: creating w3mimg/Makefile
config.status: creating w3mimg/fb/Makefile
config.status: creating w3mimg/x11/Makefile
config.status: creating w3mimg/win/Makefile
config.status: creating w3mhelp-w3m_en.html
config.status: creating w3mhelp-w3m_ja.html
config.status: creating w3mhelp-lynx_en.html
config.status: creating w3mhelp-lynx_ja.html
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile

**Comment by tats** [comment]
> The environment is debian

So you may install the build depending packages by `apt-get build-dep w3m`
to install libncurses5-dev, libssl-dev, libgc-dev, etc.

**Comment by Boruch-Baum** [comment]
That did the trick. I thought I had all dev libs accounted for.
