### ISSUE TITLE
Stack seems smashed with large image inside table

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#8]
How to reproduce
```
$ echo '<table>0<td rowspan=0 colspan=30><img width=900000 src=0 height=0>'  | ./w3m -T text/html -dump > /dev/null
*** stack smashing detected ***: ./w3m terminated
```
The behavior is not stable. w3m sometimes crashes and sometimes doesn't.
Usually It just segfault and sometimes stack protector says stack smashed.

I haven't debugged it, so I don't know why it's unstable and how the stack smashed. Following is my steps to compile w3m:
```
env AFL_HARDEN=1 AFL_USE_ASAN=1 CC=afl-clang-fast ./configure --enable-image=no
make
```

This is found by afl-fuzz.

**Comment by kcwu** [comment]
Feel free to let me know If you cannot reproduce this issue --- I could try to find more reliable input.

p.s. No hurry, I am not pushing you. Just friendly offer help if needed.

**Comment by tats** [comment]
Unreproducible for my environment with a casual try.
So more information and/or patches are welcome.

**Comment by kcwu** [comment]
While I have seen lots of crashes with table colspan (actually, they are majority of crashes), I cannot always reproduce them. They seem sensitive to environment variable and compiler options, etc.  With some environment, I can always reproduce crash. But it may not crash anymore if env changed.

I will try to produce reliable case. In the meantime, maybe you could fix https://github.com/tats/w3m/issues/16. Hope fixing it will reduce non-deterministic factor.

**Comment by tats** [comment]
Fixed by https://github.com/tats/w3m/pull/19
