### ISSUE TITLE
Incorporate converted CVS history from sf.net/p/w3m

### ISSUE THREAD

**Issue by mackyle** [tats/w3m#90]
I found this project when looking for a more up-to-date
version of w3m.  Thank you for maintaining it, the tarball
from the latest "v0.5.3+git........" tag was very helpful.  :)

However, I also wanted to be able to access the w3m commit
history leading up to the current version and discovered that
it's only available from sf.net in CVS.

Not wanting to be stuck using CVS for that I converted the
history from CVS to Git (using cvs2svn + git-svn) being careful
to use the correct author idents so that the original four
committers on sf.net which all have accounts here on GitHub
(@ukai, @satodainu, @htrb and @akinori-ito) have their commits
in the converted repository correctly attributed to them.

I have pushed the result to https://github.com/mackyle/w3m-sf

To see how good a job I did with the conversion, I compared
the release-0-5-3 tag from w3m-sf to the upstream/0.5.3 tag in this
repository.  Unfortunately since the w3m-0.5.3 tarball included
various "garbage" CVS files (that have since been removed from this
repository by commit 620796f8d750 "Remove garbage files") it's
necessary to exclude those files from the diff.

Git provides a mechanism to do this and using it like so:

    # immediately obvious syntax, yes?  ;)
    git diff release-0-5-3 upstream/0.5.3 -- :/ \
      ':(glob,exclude)**/CVS/**' ':(glob,exclude)**/.#*' \
      ':(glob,exclude)**/.cvsignore'

Shows them to be identical except for those excluded items.

The same comparision on "upstream" from this repository with
"master" from w3m-sf also yields no differences.  Note that the
w3m-sf repository does not include any of the .cvsignore files.

Since this repository has become the de facto home of the most
current w3m releases it seems like it would be beneficial to
have all the original w3m history available for things like running
bisect and other history inspection tasks.

One minimally disruptive way to include the history would be to
simply perform a "git merge -s ours" on the upstream branch of this
repository merging in the master branch of w3m-sf and perhaps also
including the release-* tags from the w3m-sf repository in this
one (maybe relocating them to be under upstream/ to avoid confusion).

The following sequence of git commands performed on this repository
would accomplish such a thing without leaving any turds behind:

    git config remote.w3m-sf.url https://github.com/mackyle/w3m-sf.git
    git config remote.w3m-sf.tagOpt --no-tags
    git config remote.w3m-sf.fetch \
      'refs/heads/master:refs/remotes/w3m-sf/master'
    git config --add remote.w3m-sf.fetch \
      'refs/tags/release-*:refs/tags/upstream/release-*'
    git fetch w3m-sf
    git checkout upstream
    # omit the --allow-unrelated-histories option for Git versions before 2.9
    git merge --allow-unrelated-histories \
      -m 'attach converted w3m cvs history' -s ours w3m-sf/master
    git config --remove-section remote.w3m-sf
    git update-ref -d refs/remotes/w3m-sf/master

This leaves the --first-parent history of the upstream branch unperturbed.

Replacing only the "git merge" command above with this sequence:

    git update-ref HEAD $(git commit-tree w3m-sf/master^{tree} \
      -p w3m-sf/master -p HEAD -m 'attach converted w3m cvs history')
    git checkout -f HEAD # will remove .cvsignore files from worktree

would make w3m-sf/master the --first-parent of the merge (instead of
upstream) and have the side-effect of removing the .cvsignore files.

This variation:

    git update-ref HEAD $(git commit-tree HEAD^{tree} \
      -p w3m-sf/master -p HEAD -m 'attach converted w3m cvs history')

also makes w3m-sf/master the --first-parent but keeps the existing tree
from the upstream branch thereby retaining the .cvsignore files.

**Comment by tats** [comment]
Finally, I've merged the original version converted by git-cvsimport
including original email addresses.

**Comment by Boruch-Baum** [comment]
On 2020-09-09 06:25, Tatsuya Kinoshita wrote:
>    Finally, I've merged the original version converted by git-cvsimport
>    including original email addresses.

Worthy to congratulate. I remember all the fear and triple-checking when
I decided to do it for my projects. I will always have fond
far-long-ago-distant memories of CVS, as long as they remain
far-long-ago-distant.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
