### ISSUE TITLE
w3m(-img)+tmux mouse integration

### ISSUE THREAD

**Issue by debdrup** [tats/w3m#98]
Would it be possible to investigate what's causing w3ms mouse mode to stop working when used in tmux with mouse-mode either turned on or off, and perhaps fix it? I have no idea what's causing it; been trying to look through the code to isolate it, and haven't had any chances whatsoever. It doesn't seem as if w3m gets the input if it's run in tmux, from what I can find - but that might just be a red herring.

**Comment by rkta** [comment]
Workaround: Use `TERM=xterm w3m`.

This works with mouse mode enable or disabled in tmux.

JFTR: w3m gets the input, but the input is not what is expected.

**Comment by debdrup** [comment]
Thanks for following up!

I don't know what changed, but in between filing this issue and the response just now, mouse mode in w3m with tmux also configured to use mouse mode has started working for me, so I consider this fixed by circumstances.

**Comment by OilSubjectLoss7** [comment]
> Would it be possible to investigate what's causing w3ms mouse mode to stop working when used in tmux with mouse-mode either turned on or off, and perhaps fix it? I have no idea what's causing it; been trying to look through the code to isolate it, and haven't had any chances whatsoever. It doesn't seem as if w3m gets the input if it's run in tmux, from what I can find - but that might just be a red herring.



> Workaround: Use `TERM=xterm w3m`.
> 
> This works with mouse mode enable or disabled in tmux.
> 
> JFTR: w3m gets the input, but the input is not what is expected.



> Workaround: Use `TERM=xterm w3m`.
> 
> This works with mouse mode enable or disabled in tmux.
> 
> JFTR: w3m gets the input, but the input is not what is expected.

How do i do this exactly?

**Comment by rkta** [comment]
> > Would it be possible to investigate what's causing w3ms mouse mode to stop working when used in tmux with mouse-mode either turned on or off, and perhaps fix it? I have no idea what's causing it; been trying to look through the code to isolate it, and haven't had any chances whatsoever. It doesn't seem as if w3m gets the input if it's run in tmux, from what I can find - but that might just be a red herring.
> 
> > Workaround: Use `TERM=xterm w3m`.
> > This works with mouse mode enable or disabled in tmux.
> > JFTR: w3m gets the input, but the input is not what is expected.
> 
> > Workaround: Use `TERM=xterm w3m`.
> > This works with mouse mode enable or disabled in tmux.
> > JFTR: w3m gets the input, but the input is not what is expected.
> 
> How do i do this exactly?

Do what exactly?
